development:
  clients:
    default:
      database: library_exercise_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: library_exercise_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV['MLAB_URI'] %>
      options:
        connect_timeout: 15
